version: '3.8'

services:
  bookkeeper-db:
    container_name: bookkeeper-db
    hostname: bookkeeper-db
    image: nouchka/sqlite3:latest
    env_file:
      - ./app/.env
    
    # networks: # for postgresql
    #   - bookkeeper-main-net
    # expose: # for postgresql
    #   - "5432"
    # ports: # for postgresql
    #   - "5432:5432"

    volumes: # for sqlite3
      - ./data/db:/root/db/

    # volumes: # for postgresql
    #   - "db-data:/var/lib/postgresql/data"
    # command: -p 5432 # for postgresql

  bookkeeper-app:
    container_name: bookkeeper-app
    hostname: bookkeeper-app
    build: 
      context: ./app
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    environment:
      - "MIGRATIONS=1"
    volumes:
      - ./app:/app
    ports:
      - "0.0.0.0:8006:8006"
    restart: always
    depends_on:
      - bookkeeper-db
    working_dir: /app
    networks:
      - bookkeeper-main-net


# volumes: # for postgresql
#   db-data:
#     driver: local

networks:
  bookkeeper-main-net:
    driver: bridge
