# Generated by Django 4.0.4 on 2022-05-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('date_of_death', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone_no', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('genre', models.CharField(choices=[('1', 'Fiction'), ('2', 'Classic'), ('3', 'Mystery'), ('4', 'Fantasy'), ('5', 'Historical'), ('6', 'Horror'), ('7', 'Literary'), ('8', 'Romance'), ('9', 'Biography'), ('10', 'Autobiography'), ('11', 'Poetry'), ('12', 'Scientific'), ('13', 'Dystopian')], default='13', max_length=3)),
                ('format', models.CharField(choices=[('1', 'ebook'), ('2', 'audiobook'), ('3', 'hardcover'), ('4', 'paperback'), ('5', 'epub'), ('6', 'kindle')], default='1', max_length=3)),
                ('page_no', models.IntegerField()),
                ('is_readed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.author')),
                ('note', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booktracker.notebook')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.publisher')),
            ],
        ),
    ]
