# Generated by Django 4.0.4 on 2022-05-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0002_book_publish_date_alter_book_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(auto_now_add=True),
        ),
    ]
