# Generated by Django 4.0.4 on 2022-05-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0006_alter_book_author_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
