# Generated by Django 4.0.4 on 2022-05-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0007_alter_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
