# Generated by Django 4.0.4 on 2022-05-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0008_rename_publish_date_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
