# Generated by Django 4.0.4 on 2022-05-12 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0015_alter_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title', 'publisher')},
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'middle_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('name', 'address', 'phone_no')},
        ),
    ]
